name: UI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: 
  contents: read
  actions: read
  checks: write
  issues: write 
  pull-requests: write 
  statuses: write

jobs:
  run-ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up .NET
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Restore .NET dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build

      # Install Node.js 
      - name: Setup Node.js 
        uses: actions/setup-node@v3 
        with: 
          node-version: '18.x'

      # Ensure browsers are installed
      - name: Install Playwright
        run: npx playwright install --with-deps

      # Run NUnit Playwright tests
      - name: Run UI tests
        run: dotnet test ${{github.workspace}}/Library.Tests.Ui/Library.Tests.Ui.csproj --logger "trx;LogFileName=test_results.trx" --results-directory ${{github.workspace}}/Library.Tests.Ui/bin/Debug/net8.0/test-results
     
      # Upload test results as artifacts
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4.4.2
        with:
          name: test-results
          path: ${{github.workspace}}/Library.Tests.Ui/bin/Debug/net8.0/test-results

  test-results:
    name: Get Test Results
    runs-on: ubuntu-latest
    needs: run-ui-tests
    steps:

      # Display test results using dorny/test-reporter
      - name: Test Reporter
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure() # Always run this step, even if previous steps fail
        with:
          artifact: test-results
          name: UI tests results
          reporter: dotnet-trx
          path: './test-results/test-results.xml'
          fail-on-error: false
